"""End-to-end hedge-fund pipeline test (monthly → daily with MA(q))."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from private_assets_frequency.core.config import (
    AssetClassConfig,
    InverseGammaPrior,
    NormalPrior,
)
from private_assets_frequency.core.protocols import AggregationType
from private_assets_frequency.pipeline.runner import (
    FrequencyPipeline,
    PipelineResult,
)
from private_assets_frequency.tests.conftest import (
    MAqSyntheticDataset,
    make_ma_hf_dataset,
)
from private_assets_frequency.utils.returns import (
    aggregate_returns,
    aggregate_returns_by_blocks,
)
from private_assets_frequency.utils.time_series import MONTH_END_FREQ


# A focused HF preset matching the conftest synthetic data exactly:
# only the factors generated by the conftest are referenced.
_HF_TEST_CFG = AssetClassConfig(
    asset_class="hedge_fund",
    smoothing_model="ma_glm",
    native_frequency="monthly",
    preprocessing=None,
    ma_lags=2,
    theta_prior="ordered_dirichlet",
    beta_priors={
        "equity_market": NormalPrior(0.4, 0.2),
        "smb": NormalPrior(0.1, 0.15),
    },
    alpha_prior=NormalPrior(0.0, 0.03),
    sigma_eps_prior=InverseGammaPrior(3.0, 0.0008),
    default_factors=("equity_market", "smb"),
    public_proxy="HFRI Equity Hedge Index",
)


def _build_hf_inputs(ds: MAqSyntheticDataset, *, drop_holidays: bool = False):
    """Wrap the conftest's MA(q) HF dataset for the pipeline.

    The pipeline's HF path needs daily factor returns for Stage 3 (Chow-Lin
    monthly → daily). Stage 3 is now calendar-aware: it aligns the daily factor
    calendar to the exact months of the monthly returns and uses the real
    per-month business-day counts as irregular blocks. So we build a genuine
    business-day index spanning exactly those months (variable days per month).

    When ``drop_holidays`` is set, a handful of business days are removed to
    emulate a real holiday-filtered calendar — the scenario the old uniform
    ratio=21 approximation could not describe (see the holiday test below).
    """
    rng = np.random.default_rng(0)
    returns = pd.DataFrame({"eq_ls": ds.observed_monthly})
    monthly_index = ds.observed_monthly.index
    first_day = monthly_index[0].to_period("M").start_time
    last_day = monthly_index[-1]
    daily_idx = pd.bdate_range(start=first_day, end=last_day)
    if drop_holidays:
        # Remove ~1 in every 37 business days (leaves every month well populated)
        keep = np.ones(len(daily_idx), dtype=bool)
        keep[::37] = False
        daily_idx = daily_idx[keep]
    n_d = len(daily_idx)
    # Daily factors: independent draws scaled to be plausible at daily freq
    daily_F = pd.DataFrame(
        {
            col: rng.normal(0.0, ds.factor_monthly[col].std() / np.sqrt(21), size=n_d)
            for col in ds.factor_monthly.columns
        },
        index=daily_idx,
    )
    return returns, ds.factor_monthly, daily_F


# ──────────────────────────────────────────────────────────────────
# End-to-end pipeline on a single HF strategy
# ──────────────────────────────────────────────────────────────────


def test_hf_pipeline_runs_end_to_end(ma_hf_dataset: MAqSyntheticDataset):
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset)
    pipe = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
        disaggregation_method="chow_lin",
        aggregation_type="multiplicative",
        fallback_policy="warn",
    )
    result = pipe.run()
    assert isinstance(result, PipelineResult)
    # For HF native=monthly, the runner produces ``monthly_returns`` populated
    # at the *daily* index (since Stage 3 disaggregates monthly→daily).
    assert "eq_ls" in result.monthly_returns.columns
    # Stage 4 doesn't run for HF (native is monthly, target is daily directly)
    assert result.daily_returns is None


def test_hf_round_trip_aggregation(ma_hf_dataset):
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset)
    pipe = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
    )
    result = pipe.run()
    # Stage 3 uses irregular monthly→daily blocks (business days per month),
    # so the round-trip must aggregate over the *actual* block sizes.
    disagg = result.per_strategy["eq_ls"].disaggregation
    block_sizes = disagg.diagnostics["block_sizes"]
    assert block_sizes is not None
    daily_out = disagg.high_frequency
    aggregated = aggregate_returns_by_blocks(
        daily_out, block_sizes, method=AggregationType.MULTIPLICATIVE
    )
    np.testing.assert_allclose(
        aggregated.to_numpy(),
        disagg.low_frequency_input.to_numpy(),
        atol=1e-10,
    )


def test_hf_pipeline_handles_holiday_filtered_calendar(ma_hf_dataset):
    """Real calendars have a variable number of business days per month.

    The old uniform ratio=21 path cut the daily factors into consecutive blocks
    of 21 rows regardless of dates. On a real calendar those blocks drift across
    month boundaries, so each "month" of daily output was compounded from the
    wrong days — silently, with errors of several percent per month (or, when
    fewer than 21·n_months days were supplied, a row-count error). The
    calendar-aware Stage 3 must keep every daily return inside its own month.
    """
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset, drop_holidays=True)
    n_m = len(returns)
    # Precondition: the real calendar does NOT contain exactly 21 days per
    # month, so the old uniform ratio=21 path (which demands len == 21 * n_m)
    # cannot describe it.
    assert len(daily_F) != 21 * n_m

    result = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
    ).run()

    disagg = result.per_strategy["eq_ls"].disaggregation
    block_sizes = np.asarray(disagg.diagnostics["block_sizes"])
    # Blocks are genuinely irregular (not all equal to 21).
    assert block_sizes.min() != block_sizes.max()
    assert int(block_sizes.sum()) == len(disagg.high_frequency)

    aggregated = aggregate_returns_by_blocks(
        disagg.high_frequency, block_sizes, method=AggregationType.MULTIPLICATIVE
    )
    np.testing.assert_allclose(
        aggregated.to_numpy(),
        disagg.low_frequency_input.to_numpy(),
        atol=1e-10,
    )
    s34 = [v for v in result.stage_validations if "Stage 3" in v.stage][0]
    assert s34.passed, f"Stage 3→4 failed: {s34.messages}"

    # The invariant that matters: every daily return carries a date inside its
    # own month, so compounding by *calendar month* reproduces the input.
    daily = disagg.high_frequency
    by_month = (1.0 + daily).groupby(daily.index.to_period("M")).prod() - 1.0
    monthly_in = disagg.low_frequency_input
    assert list(by_month.index) == list(monthly_in.index.to_period("M"))
    np.testing.assert_allclose(by_month.to_numpy(), monthly_in.to_numpy(), atol=1e-10)


def test_hf_recovers_theta_close_to_truth(ma_hf_dataset):
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset)
    result = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
    ).run()
    theta_post = result.per_strategy["eq_ls"].desmoothed.smoothing_params["theta"]
    np.testing.assert_allclose(theta_post, ma_hf_dataset.theta, atol=0.10)


def test_hf_stage_validations_recorded(ma_hf_dataset):
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset)
    result = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
    ).run()
    stages = [v.stage for v in result.stage_validations]
    assert any("Stage 1" in s for s in stages)
    assert any("Stage 3" in s for s in stages)
    s34 = [v for v in result.stage_validations if "Stage 3" in v.stage][0]
    assert s34.passed, f"Stage 3→4 failed: {s34.messages}"
