"""End-to-end hedge-fund pipeline test (monthly → daily with MA(q))."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from private_assets_frequency.core.config import (
    AssetClassConfig,
    InverseGammaPrior,
    NormalPrior,
)
from private_assets_frequency.core.protocols import AggregationType
from private_assets_frequency.pipeline.runner import (
    FrequencyPipeline,
    PipelineResult,
)
from private_assets_frequency.tests.conftest import (
    MAqSyntheticDataset,
    make_ma_hf_dataset,
)
from private_assets_frequency.utils.returns import aggregate_returns
from private_assets_frequency.utils.time_series import MONTH_END_FREQ


# A focused HF preset matching the conftest synthetic data exactly:
# only the factors generated by the conftest are referenced.
_HF_TEST_CFG = AssetClassConfig(
    asset_class="hedge_fund",
    smoothing_model="ma_glm",
    native_frequency="monthly",
    preprocessing=None,
    ma_lags=2,
    theta_prior="ordered_dirichlet",
    beta_priors={
        "equity_market": NormalPrior(0.4, 0.2),
        "smb": NormalPrior(0.1, 0.15),
    },
    alpha_prior=NormalPrior(0.0, 0.03),
    sigma_eps_prior=InverseGammaPrior(3.0, 0.0008),
    default_factors=("equity_market", "smb"),
    public_proxy="HFRI Equity Hedge Index",
)


def _build_hf_inputs(ds: MAqSyntheticDataset):
    """Wrap the conftest's MA(q) HF dataset for the pipeline.

    The pipeline's HF path needs daily factor returns for Stage 3 (Chow-Lin
    monthly → daily). We synthesise them from the monthly factors by
    splitting each monthly value evenly across the month's business days
    and adding a tiny noise term — enough to give the disaggregator a real
    indicator without polluting the round-trip aggregation property.
    """
    rng = np.random.default_rng(0)
    returns = pd.DataFrame({"eq_ls": ds.observed_monthly})
    n_m = len(ds.observed_monthly)
    # Stage 3 in the runner uses ratio=21 for monthly→daily; build a daily
    # index of exactly 21·n_m business days starting just before the first
    # monthly anchor.
    start = ds.observed_monthly.index[0] - pd.offsets.BDay(25)
    daily_idx = pd.bdate_range(start=start, periods=21 * n_m)
    n_d = len(daily_idx)
    # Daily factors: independent draws scaled to be plausible at daily freq
    daily_F = pd.DataFrame(
        {
            col: rng.normal(0.0, ds.factor_monthly[col].std() / np.sqrt(21), size=n_d)
            for col in ds.factor_monthly.columns
        },
        index=daily_idx,
    )
    return returns, ds.factor_monthly, daily_F


# ──────────────────────────────────────────────────────────────────
# End-to-end pipeline on a single HF strategy
# ──────────────────────────────────────────────────────────────────


def test_hf_pipeline_runs_end_to_end(ma_hf_dataset: MAqSyntheticDataset):
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset)
    pipe = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
        disaggregation_method="chow_lin",
        aggregation_type="multiplicative",
        fallback_policy="warn",
    )
    result = pipe.run()
    assert isinstance(result, PipelineResult)
    # For HF native=monthly, the runner produces ``monthly_returns`` populated
    # at the *daily* index (since Stage 3 disaggregates monthly→daily).
    assert "eq_ls" in result.monthly_returns.columns
    # Stage 4 doesn't run for HF (native is monthly, target is daily directly)
    assert result.daily_returns is None


def test_hf_round_trip_aggregation(ma_hf_dataset):
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset)
    pipe = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
    )
    result = pipe.run()
    # The HF Stage 3 ratio is 21 in this build (uniform-block approximation),
    # so the round-trip aggregation is enforced by ChowLinDisaggregator.
    desmoothed_m = result.per_strategy["eq_ls"].desmoothed.true_returns
    daily_out = result.monthly_returns["eq_ls"]
    # Aggregate back to monthly (ratio 21) and compare to the desmoothed monthly
    aggregated = aggregate_returns(
        daily_out, ratio=21, method=AggregationType.MULTIPLICATIVE
    )
    # The Chow-Lin disaggregator works against the *full* desmoothed series,
    # but we trim to align to the iterated head:
    n_blocks = len(aggregated)
    np.testing.assert_allclose(
        aggregated.to_numpy(),
        desmoothed_m.to_numpy()[:n_blocks],
        atol=1e-10,
    )


def test_hf_recovers_theta_close_to_truth(ma_hf_dataset):
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset)
    result = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
    ).run()
    theta_post = result.per_strategy["eq_ls"].desmoothed.smoothing_params["theta"]
    np.testing.assert_allclose(theta_post, ma_hf_dataset.theta, atol=0.10)


def test_hf_stage_validations_recorded(ma_hf_dataset):
    returns, monthly_F, daily_F = _build_hf_inputs(ma_hf_dataset)
    result = FrequencyPipeline(
        returns=returns,
        factor_returns_monthly=monthly_F,
        factor_returns_daily=daily_F,
        configs={"eq_ls": _HF_TEST_CFG},
    ).run()
    stages = [v.stage for v in result.stage_validations]
    assert any("Stage 1" in s for s in stages)
    assert any("Stage 3" in s for s in stages)
    s34 = [v for v in result.stage_validations if "Stage 3" in v.stage][0]
    assert s34.passed, f"Stage 3→4 failed: {s34.messages}"
