r"""
Predictive distributions for nowcasts: residual pools and recursive simulation.

Three mechanisms, in the order you should prefer them.

``'empirical_recursive'`` (default for models with dynamics)
    The innovation distribution is the model's own **out-of-sample** one-step
    rolling-origin errors, estimated inside the information set by
    :func:`rolling_origin_backtest`. Multi-quarter horizons are handled by
    simulation: draw ``s_Q`` from its predictive distribution, re-evaluate the
    conditional mean of ``s_{Q+1}`` at *each draw*, and add a fresh innovation.
    The horizon widening is then generated by the model's own dynamics rather
    than asserted.

``'empirical_direct'`` (default for models without dynamics)
    The predictive distribution at horizon ``h`` is the point nowcast plus a
    resample of the out-of-sample errors *at that same horizon*. Appropriate
    when the model has no internal dynamics to propagate — a carry-forward
    baseline — and useful everywhere as a cross-check (see below).

``'parametric'``
    Gaussian with the regression's prediction variance
    :math:`\hat\sigma^2 (1 + x'(X'X)^{-1}x)`, optionally convolved with
    posterior parameter uncertainty. Narrower and smoother than the empirical
    pools, and wrong in the left tail of real private markets data.

Why recursion uses the one-step pool
------------------------------------
The module spec asks for two things that pull against each other: residuals
drawn from the out-of-sample errors *at the same horizon*, and recursive
simulation for ``h >= 2``. Doing both at once double counts — the historical
``h=2`` errors were themselves produced by a nowcast that plugged in an ``h=1``
nowcast, so they already contain the accumulated uncertainty that the recursion
is about to add again.

The resolution here: recursion is the mechanism, and the innovation at *every*
step of the recursion is drawn from the **one-step** pool. For the smoothing
regression :math:`s_Q = a + b F_Q + c\, s_{Q-1} + e_Q` this reproduces the
analytic answer exactly — :math:`\mathrm{Var}(h{=}2) = \sigma_e^2 (1 + c^2)`,
so with :math:`c = \lambda \approx 0.6` the ``h=2`` interval is about 17 %
wider — without any double counting.

The literal horizon-matched reading remains available as
``'empirical_direct'``, and is not merely a fallback: recursion with i.i.d.
one-step innovations assumes the model is correctly specified, whereas the
direct pool absorbs compounding misspecification. Every recursive result
therefore carries ``diagnostics['interval_80_direct']`` when a direct pool
exists, so a materially wider direct interval is visible as a misspecification
signal instead of being hidden by the choice of method.

The pool is not centred
-----------------------
Out-of-sample errors in a small sample have a non-zero mean, and that mean is
kept. The spec's wording — "point forecast + residuals drawn from that model's
own out-of-sample rolling-origin errors" — is taken literally: the predictive
distribution answers "where will the realisation fall", and the model's own
historical bias is part of that answer. The consequence is that ``point`` is the
model's raw forecast while the draws sit ``mean(pool)`` away from it, so
``point`` is not the centre of its own interval.

That is deliberate, and the alternative is worse: centring the pool would
silently bias-correct the point forecast's *interval* while leaving the point
forecast itself uncorrected, which is the least coherent of the three options.
Every result therefore carries ``diagnostics['pool_mean']`` so the gap is
visible and attributable, and the evaluation harness reports mean error as a
separate metric rather than letting it hide inside the interval.

Small-sample fallback
---------------------
A pool with fewer than ``min_oos`` (default 20) out-of-sample errors is not an
empirical distribution, it is noise. Below that threshold the pool falls back to
in-sample residuals inflated by :math:`\sqrt{1 + p/n}` — the standard
degrees-of-freedom correction for the fact that in-sample residuals are
shrunk toward zero by the ``p`` fitted parameters — and the result's
``interval_method`` is suffixed ``'+in_sample_inflated'`` so the weaker basis
travels with the number.

References
----------
.. [1] Efron & Tibshirani (1993) — *An Introduction to the Bootstrap*, on
       resampling residuals for prediction intervals.
.. [2] Tashman (2000) — "Out-of-sample tests of forecasting accuracy,"
       *International Journal of Forecasting*. Rolling-origin evaluation.
"""

from __future__ import annotations

import warnings
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from typing import Any, Literal

import numpy as np

__all__ = [
    "DEFAULT_MIN_OOS",
    "InnovationSampler",
    "IntervalMethod",
    "ResidualPool",
    "ResidualPoolWarning",
    "build_residual_pool",
    "empirical_interval",
    "point_chain",
    "recursive_predictive_draws",
    "rolling_origin_backtest",
]


DEFAULT_MIN_OOS = 20
"""Minimum out-of-sample errors for a pool to be used as an empirical law."""

IntervalMethod = Literal["empirical_recursive", "empirical_direct", "parametric"]

InnovationSampler = Callable[[int, int, np.random.Generator], np.ndarray]
"""``(step_horizon, size, rng) -> innovations`` — see :func:`recursive_predictive_draws`."""


class ResidualPoolWarning(UserWarning):
    """Emitted when a predictive distribution rests on a weaker basis than asked."""


# ──────────────────────────────────────────────────────────────────
# Residual pool
# ──────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class ResidualPool:
    """Per-horizon error distributions backing a model's prediction intervals.

    Attributes
    ----------
    errors
        ``{horizon: errors}``. Each array holds ``actual - predicted`` at that
        horizon, either from the rolling-origin backtest or — when too few of
        those exist — from inflated in-sample residuals.
    source
        ``{horizon: 'oos' | 'in_sample_inflated'}``.
    n_oos
        ``{horizon: n}`` out-of-sample errors actually available, *before* any
        fallback. The honest count.
    inflation
        The :math:`\\sqrt{1 + p/n}` factor applied to in-sample residuals.
    min_oos
        Threshold below which the fallback engaged.
    diagnostics
        Free-form provenance, surfaced in every ``NowcastResult``.
    """

    errors: dict[int, np.ndarray]
    source: dict[int, str]
    n_oos: dict[int, int]
    inflation: float
    min_oos: int
    diagnostics: dict[str, Any] = field(default_factory=dict)

    def has(self, horizon: int) -> bool:
        """Whether a pool exists for ``horizon``."""
        return horizon in self.errors and self.errors[horizon].size > 0

    def sample(
        self, horizon: int, size: int, rng: np.random.Generator
    ) -> np.ndarray:
        """Resample ``size`` innovations for ``horizon``, with replacement.

        Parameters
        ----------
        horizon
            Horizon whose pool to draw from.
        size
            Number of draws.
        rng
            Generator.

        Returns
        -------
        np.ndarray
            Shape ``(size,)``.

        Raises
        ------
        KeyError
            If no pool exists for ``horizon``. Callers check :meth:`has` first;
            there is no silent substitution of one horizon's errors for
            another's.
        """
        if not self.has(horizon):
            raise KeyError(
                f"no residual pool at horizon {horizon}; available: "
                f"{sorted(h for h in self.errors if self.errors[h].size)}."
            )
        pool = self.errors[horizon]
        return pool[rng.integers(0, pool.size, size=size)]

    def sampler(self, horizon: int) -> InnovationSampler:
        """A fixed-horizon innovation sampler for :func:`recursive_predictive_draws`.

        Parameters
        ----------
        horizon
            Horizon whose pool every call should draw from, regardless of the
            recursion step. Pass ``1`` for the one-step innovation law.

        Returns
        -------
        Callable
            ``(step_horizon, size, rng) -> np.ndarray``. ``step_horizon`` is
            accepted and ignored, which is the point: the recursion generates
            horizon widening through the model's dynamics, not by switching
            pools.
        """
        if not self.has(horizon):
            raise KeyError(f"no residual pool at horizon {horizon}.")

        def _sample(step_horizon: int, size: int, rng: np.random.Generator) -> np.ndarray:
            return self.sample(horizon, size, rng)

        return _sample

    def scale(self, horizon: int) -> float:
        """Standard deviation of the pool at ``horizon``."""
        if not self.has(horizon):
            raise KeyError(f"no residual pool at horizon {horizon}.")
        pool = self.errors[horizon]
        return float(np.std(pool, ddof=1)) if pool.size > 1 else float(abs(pool[0]))

    def is_fallback(self, horizon: int) -> bool:
        """Whether ``horizon`` is backed by inflated in-sample residuals."""
        return self.source.get(horizon) == "in_sample_inflated"

    def method_suffix(self, horizons: Sequence[int]) -> str:
        """``'+in_sample_inflated'`` if any of ``horizons`` used the fallback."""
        if any(self.is_fallback(h) for h in horizons):
            return "+in_sample_inflated"
        return ""


def build_residual_pool(
    oos_errors: dict[int, np.ndarray] | None,
    in_sample_residuals: np.ndarray,
    *,
    n_params: int,
    horizons: Sequence[int],
    min_oos: int = DEFAULT_MIN_OOS,
    warn: bool = True,
    label: str = "nowcaster",
) -> ResidualPool:
    r"""Assemble per-horizon error pools, falling back when the OOS count is thin.

    Parameters
    ----------
    oos_errors
        ``{horizon: errors}`` from :func:`rolling_origin_backtest`, or ``None``.
    in_sample_residuals
        Residuals of the final fit, used for the fallback.
    n_params
        Number of fitted parameters ``p``, for the
        :math:`\sqrt{1 + p/n}` inflation.
    horizons
        Horizons a pool is needed for.
    min_oos
        Below this many out-of-sample errors, fall back.
    warn
        Emit :class:`ResidualPoolWarning` when the fallback engages.
    label
        Model name, for the warning text.

    Returns
    -------
    ResidualPool

    Raises
    ------
    ValueError
        If neither out-of-sample errors nor usable in-sample residuals exist for
        a requested horizon — there is then no basis for an interval at all, and
        returning a point estimate dressed as a distribution would be worse.

    Notes
    -----
    The inflation factor corrects the *scale* of in-sample residuals but not
    their *shape*: they remain the residuals of a fit that saw the data, and
    they understate genuine forecast error from parameter instability and regime
    change. The suffix on ``interval_method`` exists so that caveat is visible
    downstream rather than only here.
    """
    resid = np.asarray(in_sample_residuals, dtype=float).reshape(-1)
    resid = resid[np.isfinite(resid)]
    n = resid.size
    inflation = float(np.sqrt(1.0 + n_params / n)) if n > 0 else float("nan")
    inflated = resid * inflation if n > 0 else resid

    errors: dict[int, np.ndarray] = {}
    source: dict[int, str] = {}
    n_oos: dict[int, int] = {}
    fell_back: list[int] = []

    for h in sorted(set(int(x) for x in horizons)):
        pool = (
            np.asarray(oos_errors.get(h, np.empty(0)), dtype=float).reshape(-1)
            if oos_errors
            else np.empty(0)
        )
        pool = pool[np.isfinite(pool)]
        n_oos[h] = int(pool.size)
        if pool.size >= min_oos:
            errors[h] = pool
            source[h] = "oos"
            continue
        if inflated.size == 0:
            raise ValueError(
                f"{label}: horizon {h} has {pool.size} out-of-sample errors "
                f"(need {min_oos}) and no usable in-sample residuals; there is "
                "no basis for a prediction interval."
            )
        errors[h] = inflated
        source[h] = "in_sample_inflated"
        fell_back.append(h)

    if fell_back and warn:
        warnings.warn(
            f"{label}: horizons {fell_back} have fewer than {min_oos} "
            "out-of-sample rolling-origin errors, so their prediction intervals "
            f"fall back to in-sample residuals inflated by sqrt(1 + p/n) = "
            f"{inflation:.3f}. In-sample residuals understate forecast error "
            "from parameter instability and regime change; treat the intervals "
            "as a lower bound on uncertainty.",
            ResidualPoolWarning,
            stacklevel=2,
        )

    return ResidualPool(
        errors=errors,
        source=source,
        n_oos=n_oos,
        inflation=inflation,
        min_oos=int(min_oos),
        diagnostics={
            "n_in_sample_residuals": int(n),
            "in_sample_inflation": inflation,
            "n_oos_by_horizon": dict(n_oos),
            "source_by_horizon": dict(source),
            "fallback_horizons": fell_back,
            "min_oos": int(min_oos),
        },
    )


# ──────────────────────────────────────────────────────────────────
# Rolling-origin backtest (inside an information set)
# ──────────────────────────────────────────────────────────────────


def rolling_origin_backtest(
    actual: np.ndarray,
    *,
    min_train: int,
    horizons: Sequence[int],
    predict_fn: Callable[[int, Sequence[int]], dict[int, float]],
    max_origins: int | None = None,
) -> tuple[dict[int, np.ndarray], dict[str, Any]]:
    r"""Expanding-window backtest producing out-of-sample errors by horizon.

    For each origin ``o`` the callable is given the number of training rows —
    rows ``[0, o)`` — and returns a nowcast for rows ``o, o+1, …`` at the
    requested horizons. The error at horizon ``h`` is
    ``actual[o + h - 1] - prediction[h]``.

    This runs **inside** an information set: ``actual`` holds published rows
    only, so no origin can see an unpublished quarter, and ``predict_fn`` is
    expected to re-estimate everything from ``[0, o)`` on each call. The
    expense is the point — reusing a single global fit is the leak this function
    exists to avoid.

    Parameters
    ----------
    actual
        Realised values, in time order.
    min_train
        Smallest training window. Origins start here.
    horizons
        Horizons to score.
    predict_fn
        ``predict_fn(n_train, horizons) -> {horizon: prediction}``. May return a
        partial mapping or ``NaN`` to decline an origin (e.g. a singular design);
        declined origins are counted in the diagnostics and skipped.
    max_origins
        Keep only the most recent ``max_origins`` origins. ``None`` uses all of
        them. Useful when ``predict_fn`` is expensive, at the cost of a thinner
        pool.

    Returns
    -------
    errors : dict[int, np.ndarray]
        Out-of-sample errors per horizon.
    diagnostics : dict
        Origin counts, skipped origins, and the training-window range.

    Notes
    -----
    Errors are *not* aligned across horizons: the ``h=1`` pool has one more
    entry than the ``h=2`` pool, because the last origin has no second target.
    Each pool is used independently, so this is harmless.
    """
    y = np.asarray(actual, dtype=float).reshape(-1)
    n = y.size
    hs = sorted(set(int(h) for h in horizons))
    if min_train < 1:
        raise ValueError(f"min_train must be >= 1, got {min_train}.")
    if not hs or min(hs) < 1:
        raise ValueError(f"horizons must all be >= 1, got {list(horizons)!r}.")

    origins = list(range(min_train, n))
    if max_origins is not None:
        if max_origins < 1:
            raise ValueError(f"max_origins must be >= 1, got {max_origins}.")
        origins = origins[-max_origins:]

    collected: dict[int, list[float]] = {h: [] for h in hs}
    n_skipped = 0
    n_declined: dict[int, int] = {h: 0 for h in hs}

    for o in origins:
        feasible = [h for h in hs if o + h - 1 < n]
        if not feasible:
            continue
        try:
            preds = predict_fn(o, feasible)
        except Exception:  # noqa: BLE001 - an origin may be unfittable
            n_skipped += 1
            continue
        if preds is None:
            n_skipped += 1
            continue
        for h in feasible:
            pred = preds.get(h, np.nan)
            if pred is None or not np.isfinite(pred):
                n_declined[h] += 1
                continue
            collected[h].append(float(y[o + h - 1] - pred))

    errors = {h: np.asarray(v, dtype=float) for h, v in collected.items()}
    diagnostics = {
        "n_origins_attempted": len(origins),
        "n_origins_skipped": n_skipped,
        "n_declined_by_horizon": n_declined,
        "n_errors_by_horizon": {h: int(v.size) for h, v in errors.items()},
        "min_train": int(min_train),
        "first_origin": origins[0] if origins else None,
        "last_origin": origins[-1] if origins else None,
        "n_rows": int(n),
    }
    return errors, diagnostics


# ──────────────────────────────────────────────────────────────────
# Recursive predictive simulation
# ──────────────────────────────────────────────────────────────────


def recursive_predictive_draws(
    *,
    horizons: Sequence[int],
    conditional_mean: Callable[[int, np.ndarray], np.ndarray],
    history: np.ndarray,
    innovation_sampler: InnovationSampler,
    n_draws: int,
    rng: np.random.Generator,
) -> dict[int, np.ndarray]:
    r"""Simulate the predictive distribution recursively across horizons.

    .. code-block:: text

        h = 1:  draws₁ = m(1, history)          + e₁
        h = 2:  draws₂ = m(2, [draws₁, history]) + e₂
        h = 3:  draws₃ = m(3, [draws₂, draws₁, …]) + e₃

    with every ``eₕ`` an independent resample of the one-step innovation pool.
    The conditional mean is re-evaluated at *each draw* rather than at the point
    forecast, which is what makes the ``h >= 2`` interval reflect the
    uncertainty in the ``h = 1`` value it conditions on.

    Parameters
    ----------
    horizons
        Horizons to simulate, which must be ``1, 2, …, H`` with no gaps: a
        recursion cannot skip a step, because horizon ``h`` conditions on
        horizon ``h - 1``.
    conditional_mean
        ``conditional_mean(horizon, history) -> np.ndarray`` of shape
        ``(n_draws,)``. ``history`` has shape ``(n_draws, n_lags)`` with column
        ``0`` the most recent reported value, column ``1`` the one before it,
        and so on. Must be vectorised over rows.
    history
        Initial lag history, shape ``(n_lags,)`` or ``(n_draws, n_lags)``. A 1-D
        array of known published values is broadcast across draws.
    innovation_sampler
        ``(step_horizon, size, rng) -> np.ndarray`` supplying the innovation
        added at each step. :meth:`ResidualPool.sampler` adapts an empirical
        pool — pass ``pool.sampler(1)`` for the one-step law, which is the
        default throughout this package and the reason the module docstring
        gives. A model with a parametric predictive variance supplies its own
        Gaussian sampler here instead.
    n_draws
        Number of draws.
    rng
        Generator.

    Returns
    -------
    draws : dict[int, np.ndarray]
        ``{horizon: draws}``, each of shape ``(n_draws,)``.

    See Also
    --------
    point_chain : the matching point forecast, which chains the same
        ``conditional_mean`` with zero innovations.

    Raises
    ------
    ValueError
        If ``horizons`` is not contiguous from 1, or shapes do not line up.
    """
    hs = sorted(set(int(h) for h in horizons))
    if hs != list(range(1, len(hs) + 1)):
        raise ValueError(
            "recursive simulation needs contiguous horizons 1..H (horizon h "
            f"conditions on h-1); got {hs}."
        )
    if n_draws < 1:
        raise ValueError(f"n_draws must be >= 1, got {n_draws}.")
    hist = np.asarray(history, dtype=float)
    if hist.ndim == 1:
        hist = np.tile(hist.reshape(1, -1), (n_draws, 1))
    elif hist.ndim == 2:
        if hist.shape[0] != n_draws:
            raise ValueError(
                f"history has {hist.shape[0]} rows but n_draws={n_draws}."
            )
        hist = hist.copy()
    else:
        raise ValueError(f"history must be 1-D or 2-D, got {hist.ndim}-D.")
    n_lags = hist.shape[1]

    draws: dict[int, np.ndarray] = {}

    for h in hs:
        mean = np.asarray(conditional_mean(h, hist), dtype=float).reshape(-1)
        if mean.size != n_draws:
            raise ValueError(
                f"conditional_mean at horizon {h} returned {mean.size} values, "
                f"expected {n_draws}."
            )
        drawn = mean + np.asarray(
            innovation_sampler(h, n_draws, rng), dtype=float
        ).reshape(-1)
        draws[h] = drawn
        if n_lags > 0:
            hist = np.concatenate(
                [drawn.reshape(-1, 1), hist[:, : n_lags - 1]], axis=1
            )

    return draws


def point_chain(
    *,
    horizons: Sequence[int],
    conditional_mean: Callable[[int, np.ndarray], np.ndarray],
    history: np.ndarray,
) -> dict[int, float]:
    """Point forecasts from chaining ``conditional_mean`` with zero innovations.

    The deterministic counterpart of :func:`recursive_predictive_draws`: horizon
    ``h`` conditions on the *point* forecast for ``h - 1`` rather than on a
    draw. For a linear conditional mean this is the conditional expectation, and
    therefore equals the mean of the simulated draws up to simulation error.

    Parameters
    ----------
    horizons
        Contiguous horizons ``1..H``.
    conditional_mean
        As in :func:`recursive_predictive_draws`, called with a single-row
        history.
    history
        Known lag history, shape ``(n_lags,)``.

    Returns
    -------
    dict[int, float]
        ``{horizon: point}``.
    """
    hs = sorted(set(int(h) for h in horizons))
    if hs != list(range(1, len(hs) + 1)):
        raise ValueError(f"point_chain needs contiguous horizons 1..H; got {hs}.")
    hist = np.asarray(history, dtype=float).reshape(1, -1)
    n_lags = hist.shape[1]
    points: dict[int, float] = {}
    for h in hs:
        mean = np.asarray(conditional_mean(h, hist), dtype=float).reshape(-1)
        points[h] = float(mean[0])
        if n_lags > 0:
            hist = np.concatenate(
                [np.array([[points[h]]]), hist[:, : n_lags - 1]], axis=1
            )
    return points


def empirical_interval(
    draws: np.ndarray, level: float = 0.80
) -> tuple[float, float]:
    """Equal-tailed empirical interval of ``draws`` at nominal ``level``.

    Parameters
    ----------
    draws
        Predictive draws.
    level
        Nominal coverage in ``(0, 1)``.

    Returns
    -------
    tuple[float, float]
        ``(lower, upper)``.
    """
    if not 0.0 < level < 1.0:
        raise ValueError(f"level must be in (0, 1), got {level!r}.")
    tail = (1.0 - level) / 2.0
    lo, hi = np.quantile(np.asarray(draws, dtype=float), [tail, 1.0 - tail])
    return float(lo), float(hi)
